# Generated by Django 4.2.6 on 2023-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='ref_no',
            field=models.IntegerField(default=100),
        ),
    ]
