# Generated by Django 4.2.6 on 2023-10-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_grievance_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='about',
            field=models.CharField(default='No Value', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='handler',
            field=models.BooleanField(default=False),
        ),
    ]
