# Generated by Django 4.2.6 on 2023-10-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_grievance_about_user_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NORMAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('UNDER REVIEW', 'Under Review'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=100),
        ),
    ]
