# Generated by Django 4.2.6 on 2023-10-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_grievance_priority_alter_grievance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.IntegerField(default=100)),
                ('reason', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NORMAL', max_length=100)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance', to='app.grievance')),
            ],
        ),
    ]
