# Generated by Django 4.2.6 on 2023-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_escalate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalate',
            name='grievance',
        ),
    ]
