# Generated by Django 4.2.6 on 2023-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_escalate_grievance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalate',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('UNDER REVIEW', 'Under Review'), ('CLOSED', 'Closed')], default='Registered', max_length=100),
        ),
    ]
