# Generated by Django 4.2.7 on 2023-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_escalate_priority_alter_grievance_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalate',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Closed', 'Closed')], default='Registered', max_length=100),
        ),
    ]
