# Generated by Django 4.2.7 on 2023-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_escalate_priority_alter_grievance_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='handler_response',
            field=models.CharField(default='', max_length=500),
        ),
    ]
